version: '3'
services: 
        nodeapp:
                image: harshrai3112/yelpcamp:1.0
                ports:
                        - 3000:3000
                restart: always
                depends_on:
                        - mongo
        mongo:
                image: mongo
                ports:
                        - 27017:27107
